### ISSUE TITLE
Write a Java SDK for merchants

### ISSUE THREAD

**Issue by ruphy** [italia/18app-java-sdk#1]
The documentation, test files and a description of the test environment are available here:

[Progetto18app.zip](https://github.com/italia/18app-dotnet-sdk/files/1356869/Progetto18app.zip)
[WS_VerificaVoucher.zip](https://github.com/italia/18app-dotnet-sdk/files/1356870/WS_VerificaVoucher.zip)
[Linee Guida Esercenti_ottobre 2016.pdf](https://github.com/italia/18app-dotnet-sdk/files/1356867/Linee.Guida.Esercenti_ottobre.2016.pdf)

**Comment by vivadaniele** [comment]
@ruphy can you have any additional information about what you want?

**Comment by ruphy** [comment]
@vivadaniele absolutely, I am waiting for @rasky to fill in some details, but I will anticipate a few of the issues we want to tackle here.
In short - 18app has released an API for retails and stores to accept vouchers. This API allows them to validate and accept those vouchers, effectively integrating them into their payment system as valid payment means.

A very useful feature to have a wider acceptance of the vouchers within stores is an SDK, so that 3rd party software vendors can integrate it into their payment systems, web or otherwise, in a simple way. This is the Java version of the challenge. There currently exists an issue to create a .NET version as well (see https://github.com/italia/18app-dotnet-sdk/issues/1), as these are the most commonly used languages, but (upon request) we can create different SDKs in other languages too.

**Comment by alranel** [comment]
Qui spiegazioni su 18app: https://developers.italia.it/it/18app/

**Comment by RiccardoBusetti** [comment]
Io mi metto al lavoro sull'sdk
